import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "리그오브레전드 정보",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="bg-gray-800 text-white p-4">
          <nav className="flex justify-around items-center w-full py-1 font-bold">
            <Link href="/" className="hover:text-yellow-300">
              홈
            </Link>
            <Link href="/champions" className="hover:text-yellow-300">
              챔피언 목록
            </Link>
            <Link href="/items" className="hover:text-yellow-300">
              아이템 목록
            </Link>
            <Link href="/rotation" className="hover:text-yellow-300">
              챔피언 로테이션
            </Link>
          </nav>
        </header>
        <main className="flex-grow">{children}</main>
        <footer className="bg-gray-800 text-white p-4 text-center">
          © 2024 My Website. All rights reserved
        </footer>
      </body>
    </html>
  );
}
